name: publish
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Get Commit Info
        run: |
          gpg --import static/secure_keys.chain.asc
          gpg --import-ownertrust static/secure-trust
          {
              echo 'GIT_SIGNATURE_INFO<<GCATFILEEOF'
              git cat-file -p HEAD
              git log -n1 --show-signature
              echo GCATFILEEOF
            } >> "$GITHUB_ENV"
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}